apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: votehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votehub-alertmanager
  template:
    metadata:
      labels:
        app: votehub-alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
              readOnly: true
            - name: data
              mountPath: /alertmanager
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
      volumes:
        - name: config
          configMap:
            name: votehub-alertmanager-config
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-data
